<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($specificInfo):?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value):?>
            <tr>
                <th scope="row"><?= $block->escapeHtml($label) ?></th>
                <td>
                    <?= /* @noEscape */ nl2br(implode("\n", $block->getValueAsArray($value, false))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>
<?= $block->getChildHtml() ?>
